on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

      # Deploy ARM  template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./demos/private-aks-cluster-with-public-dns-zone/azuredeploy.json
        parameters: ./demos/private-aks-cluster-with-public-dns-zone/azuredeploy.parameters.json
        metadata: ./demos/private-aks-cluster-with-public-dns-zone/metadata.json
